[project]
name = "streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nhl-vis-386>=0.1.10",
    "pandas>=2.3.3",
    "streamlit>=1.51.0",
]
